name: waste_org
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python == 3.10.*
  - numpy
  - ipykernel
  - pandas
  - pytorch==2.3.1
  - torchvision==0.18.1
  - torchaudio==2.3.1
  - pytorch-cuda=11.8
  - matplotlib
  - pip == 24.0
  - pip:
    - kaggle
